### ISSUE TITLE
Is ErrSegmentTemplateLiveProfileOnly correct?

### ISSUE THREAD

**Issue by pdf** [zencoder/go-dash#25]
I can't download the spec right now, because the [ISO download](http://standards.iso.org/ittf/PubliclyAvailableStandards/c065274_ISO_IEC_23009-1_2014.zip) gives me a 403 constantly, but on-demand profile with segment templates does pass schema [validation](http://www-itec.uni-klu.ac.at/dash/?page_id=605).  I haven't tested beyond that though.

If it doesn't break the spec, it would be nice to be able to generate on-demand MPDs using a segment template, because long videos with relatively short segments means generating quite large MPDs if every segment needs to be explicitly written to a segment list.

**Comment by pdf** [comment]
Also, it seems like there's currently no way to produce segmented MPDs without using SegmentTemplate, since SegmentList is not implemented.  I'd be happy to provide a PR to either allow SegmentTemplate for on-demand, or to implement SegmentList, but the prior would be preferred if anyone can confirm what the spec says.

**Comment by GeneticGenesis** [comment]
Hi Peter,

Thanks for the issue. I completely agree that this is allowed as per the [Dash XSD](https://gist.github.com/GeneticGenesis/c5ad7db426f0f7b74de9).

However, as per ISO_23009-1-2012, section 8.3.2 (ISO Base media file format On Demand profile):
"neither the Period.SegmentList element nor the Period.SegmentTemplate element shall be present".

Dash on-demand profile forces you to use a sidx atom in your media to represent where your segment boundaries are. If you want to use segment list/timeline, you should use "live" or "main" profile. We'll have a branch locally which has segment timeline support in dash live, we can hopefully push this out later this week, but I'm not promising anything right now.

I'll close this as resolved, but raise an issue for SegmentList and SegmentTimeline support in Main/Live profile.

Cheers!

~PhilC.

**Comment by pdf** [comment]
Thanks @GeneticGenesis, I would usually just look up the spec myself, if ISO wasn't denying access to their 'publicly available' standards :confused:.  I may look at implementing main profile here if the spec ever becomes available again, since that appears to satisfy my requirements (as far as I can tell from reading slides).

**Comment by GeneticGenesis** [comment]
No problems.

Overwhelmingly I see people using "live" profile with segment template or segment timeline for their Dash deliveries at the moment. It seems to work well in most players.

Let me know if you need any pointers or help.

Cheers,
