### ISSUE TITLE
Error parsing the attribute "start" of Period

### ISSUE THREAD

**Issue by dlecorfec** [zencoder/go-dash#38]
While trying to parse a mpd containing:
`<Period start="PT0S" id="dash">`

I get:
strconv.ParseInt: parsing "PT0S": invalid syntax

**Comment by thomshutt** [comment]
There's a PR in-flight (https://github.com/zencoder/go-dash/pull/37) that I think should solve this once it gets merged.

**Comment by dlecorfec** [comment]
Indeed, thanks for pointing it out, it works fine with it.
